title: My Personal Blog
email: eko_junaidisalam@live.com
description: > # this means to ignore newlines until "baseurl:"
  Ilmu adalah titipan `ilahi`, tak selamanya kita miliki tapi tetap harus kita cari.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <a name='more'></a>
paginate: 5
twitter_username: Eko_Junaidi_S
github_username:  ekojs
disqus:
   shortname: ekojunaidisalam
google_analytics: UA-92973163-2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
